import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navigation from "@/components/navigation/Navigation";
import MainNav from "@/components/mainnav/MainNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <p>HEADER LOGO</p>
        </header>

        <MainNav>{children}</MainNav>

        <footer>FOOTER</footer>
      </body>
    </html>
  );
}
